### ISSUE TITLE
Where can I buy teensy?

### ISSUE THREAD

**Issue by JuanPotato** [wyager/MicroMechBoard#9]
Where can I buy a teensy like the one that you used? I want to create a programmable keyboard set of 9 keys, but don't know where to get the materials.

**Comment by brendan-byrne** [comment]
https://www.pjrc.com/teensy/

On Wed, Dec 16, 2015 at 9:59 PM, Juan Potato <notifications@github.com>
wrote:

> Where can I buy a teensy like the one that you used? I want to create a
> programmable keyboard set of 9 keys, but don't know where to get the
> materials.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wyager/MicroMechBoard/issues/9>.
>



-- 

*Brendan Byrne845.642.1957*
*brendanbyrne.info <http://brendanbyrne.info/>*

**Comment by wyager** [comment]
Yep. There's a parts list in the hardware directory.

**Comment by wyager** [comment]
Let me know if you need help finding anything else. Probably better to just shoot me an email though.
